# Generated by Django 5.2 on 2026-04-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_bovedaseguridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='logroperiodo',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='logros_adjuntos/%Y/%m/', verbose_name='Archivo de Planeación'),
        ),
    ]
