# Generated by Django 5.2 on 2026-04-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_logroperiodo_archivo_adjunto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='logroperiodo',
            unique_together=set(),
        ),
    ]
