# Generated by Django 5.2 on 2026-04-23 23:34

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_logroperiodo_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='logroperiodo',
            unique_together={('curso', 'periodo', 'docente', 'materia')},
        ),
        migrations.CreateModel(
            name='SimuladorAvanzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador criptográfico inmutable.', unique=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Simulador')),
                ('slug', models.SlugField(help_text='URL amigable y optimizada para búsquedas en Edge Caching.', max_length=250, unique=True)),
                ('codigo_fuente', models.TextField(help_text='El motor de simulación autocontenido generado por la IA.', verbose_name='Código HTML/JS/CSS (Payload)')),
                ('hash_integridad', models.CharField(blank=True, editable=False, help_text='SHA-256 del código. Garantiza inmutabilidad ante ataques (Tampering).', max_length=64)),
                ('peso_bytes', models.PositiveIntegerField(default=0, editable=False, help_text='Tamaño en bytes para cálculos de optimización de ancho de banda.')),
                ('motor_ia_generador', models.CharField(default='DeepSeek-V3', help_text='Modelo cognitivo que compiló este activo.', max_length=50)),
                ('prompt_original', models.TextField(blank=True, help_text='Instrucción pedagógica exacta que dio origen a la simulación.', null=True)),
                ('costo_generacion_usd', models.DecimalField(decimal_places=6, default=0.0, help_text='Costo exacto de la API para cálculo de ROI automatizado.', max_digits=10)),
                ('vistas', models.PositiveIntegerField(db_index=True, default=0)),
                ('tiempo_promedio_segundos', models.PositiveIntegerField(default=0, help_text='Retención promedio del estudiante en la simulación.')),
                ('tasa_exito', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de usuarios que activan el triggerSuccess.', max_digits=5)),
                ('configuracion_sandbox', models.JSONField(blank=True, default=dict, help_text="Feature Policy del Iframe: {'allow_modals': False}")),
                ('metadata_pedagogica', models.JSONField(blank=True, default=dict, help_text="Indexación de contexto: {'materia': 'Física', 'dificultad': 'Alta'}")),
                ('version', models.PositiveIntegerField(default=1, help_text='Auto-versionamiento semántico.')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, editable=False, help_text='Soft Delete. Mantiene la integridad referencial en PostgreSQL.', null=True)),
            ],
            options={
                'verbose_name': 'Simulador Avanzado',
                'verbose_name_plural': 'Simuladores Avanzados',
                'ordering': ['-creado_at'],
                'indexes': [models.Index(fields=['activo', '-creado_at'], name='sim_activo_creado_idx'), models.Index(fields=['activo', '-vistas'], name='sim_activo_vistas_idx')],
            },
        ),
    ]
