# Generated by Django 5.2 on 2026-04-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_logroperiodo_unique_together_simuladoravanzado'),
    ]

    operations = [
        migrations.AddField(
            model_name='simuladoravanzado',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Resumen pedagógico para el catálogo del Hub.', null=True, verbose_name='Descripción'),
        ),
    ]
