"""
    Django settings for djangocrud project.

    Generated by 'django-admin startproject' using Django 5.2.
    Optimized for Tier-1 High Availability, Real-Time WebSockets & Persistent Cloud Volumes.
"""
import os
import dj_database_url
import ssl
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
# 🛡️ CIRUGÍA REALIZADA: Se agregó default para permitir el build en Railway sin .env
SECRET_KEY = config('SECRET_KEY', default='django-insecure-build-key-temporal-123')


# --- DETECCIÓN DINÁMICA DE ENTORNO (RAILWAY VS LOCAL) ---
IS_RAILWAY = config('RAILWAY_ENVIRONMENT', default='') != ''

if IS_RAILWAY:
    # Configuración de Producción (High Security)
    DEBUG = False
    ALLOWED_HOSTS = ['*']
    # 🛡️ CIRUGÍA REALIZADA: Unificada la configuración CSRF para evitar sobreescrituras
    CSRF_TRUSTED_ORIGINS = [
        'https://*.up.railway.app',
        'https://web-production-e3cbe.up.railway.app' # Tu dominio actual
    ]
    # Forzamos seguridad SSL en la nube
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    # Configuración de Desarrollo Local
    DEBUG = config('DEBUG', default=True, cast=bool)
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv())
    CSRF_TRUSTED_ORIGINS = ["http://localhost:8000", "http://127.0.0.1:8000"]


# Application definition
INSTALLED_APPS = [
    # ⚡ Channels y Daphne deben estar al principio para manejar runserver y WebSockets correctamente
    'daphne',
    'channels',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 🛠️ Utilidades de Frontend (Necesario para fechas amigables en el Feed)
    'django.contrib.humanize', 

    'tasks.apps.TasksConfig',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Middleware for forcing password changes
    'tasks.middleware.ForcePasswordChangeMiddleware',
    # 🛡️ Middleware de Auditoría y Seguridad (Paso 10)
    'tasks.middleware.AuditMiddleware',
]

ROOT_URLCONF = 'djangocrud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'), # Global templates
            os.path.join(BASE_DIR, 'tasks', 'templates'), # Tasks app templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media', 
                'tasks.context_processors.datos_globales_usuario', 
            ],
        },
    },
]

# Servidor WSGI (Tradicional - Fallback)
WSGI_APPLICATION = 'djangocrud.wsgi.application'

# ===================================================================
# ⚡ FASE III (PASO 11): CONFIGURACIÓN ASGI Y CHANNELS (NIVEL GOD-TIER)
# ===================================================================
# Servidor ASGI (Asíncrono para WebSockets y Tráfico FENIX_CORE)
ASGI_APPLICATION = 'djangocrud.asgi.application'

REDIS_URL = config('REDIS_URL', default=None)

if REDIS_URL:
    print("🟢 FENIX_CORE: Motor Redis detectado. Conectando sistema Pub/Sub en tiempo real...")
    
    # Configuración base del host
    redis_config = {
        "hosts": [REDIS_URL],
    }
    
    # 🛡️ BYPASS DE SEGURIDAD SSL (La clave para Cloud Deployments en Railway/AWS)
    # Si la URL de Redis usa 'rediss://', los certificados de la nube bloquearán la conexión interna.
    # Necesitamos desactivar la validación estricta (ssl_cert_reqs) para permitir el flujo del WebSockets.
    if REDIS_URL.startswith('rediss://'):
        redis_config["ssl_cert_reqs"] = ssl.CERT_NONE
        print("🟢 FENIX_CORE: Protocolo TLS/SSL seguro adaptado para clúster Redis.")

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": redis_config,
        },
    }
else:
    print("🔴 ALERTA CRÍTICA: REDIS_URL no encontrado. WebSockets en modo desarrollo (InMemory).")
    print("🔴 FENIX_CORE: El tiempo real PUEDE FALLAR si hay múltiples workers/procesos en la nube.")
    # Usamos InMemory para desarrollo local (no requiere Redis instalado)
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
# ===================================================================


# ===================================================================
# 🗄️ DATABASE CONFIGURATION
# ===================================================================
DATABASE_URL = config('DATABASE_URL', default=None)
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL, 
            conn_max_age=600, # Optimizado de 1800 a 600 para mejor reciclaje de conexiones
            conn_health_checks=True
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='learning_labs_db'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': '9967112fhr',
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }

# High security password hashers (Argon2)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 8}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ===================================================================
# 📦 STATIC FILES (CSS, JavaScript, Images)
# ===================================================================
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication paths
LOGIN_URL = '/signin/'
LOGIN_REDIRECT_URL = '/'

# ===================================================================
# 🗄️ PERSISTENT VOLUME STORAGE (ARCHIVOS SUBIDOS POR USUARIOS)
# ===================================================================
# ⚡ CIRUGÍA GOD-TIER: Se eliminó la dependencia local/efímera.
# Si el sistema detecta que está en Railway, aislará todos los archivos subidos 
# (imágenes de perfil, posts del muro, actas PDF) dentro de un disco duro externo
# conectado en la ruta '/app/media'. Si el contenedor muere, el disco sobrevive.

MEDIA_URL = '/media/'

if IS_RAILWAY:
    # ⚡ MODO PRODUCCIÓN: Apunta al disco duro blindado (Volume) montado por Railway
    MEDIA_ROOT = '/app/media'
    print("🟢 ALMACENAMIENTO: Volumen Persistente Montado en /app/media")
else:
    # 🛠️ MODO DESARROLLO LOCAL: Guarda en la carpeta tradicional de tu PC
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    print("🟡 ALMACENAMIENTO: Entorno Local (Directorio /media)")

DEFAULT_TEMP_PASSWORD = '123456'


# ==============================================================
# 🧠 CONFIGURACIÓN DE INTELIGENCIA ARTIFICIAL (Fase 4)
# ==============================================================
# 🛡️ CIRUGÍA REALIZADA: Clave protegida con default para build
DEEPSEEK_API_KEY = config('DEEPSEEK_API_KEY', default='dummy-ai-key')
AI_MODEL_NAME = "deepseek-chat"


# ... Agrega esto al final si no existe, o añade las líneas con 'T' ...
DATETIME_INPUT_FORMATS = [
    '%Y-%m-%dT%H:%M:%S',    # Formato ISO (con T)
    '%Y-%m-%dT%H:%M',       # Formato ISO corto (con T)
    '%Y-%m-%d %H:%M:%S',
    '%Y-%m-%d %H:%M:%S.%f',
    '%Y-%m-%d %H:%M',
    '%m/%d/%Y %H:%M:%S',
]

# ==========================================
# 📱 TWILIO CONFIGURATION (SMS/WHATSAPP)
# ==========================================
# 🛡️ CIRUGÍA REALIZADA: Credenciales protegidas con config() y default para build
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='dummy-sid')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='dummy-token')
# Usamos el número de WhatsApp definido en .env, si no existe, busca PHONE_NUMBER
TWILIO_PHONE_NUMBER = config('TWILIO_WHATSAPP_NUMBER', default=config('TWILIO_PHONE_NUMBER', default=''))


# Opcional: Aumentar el límite de subida para archivos históricos grandes (50MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800 
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800

# ==============================================================================
# 🧠 FENIX_CORE CACHE & SESSION MATRIX (GOD-TIER ARCHITECTURE)
# ==============================================================================
# Diseñado con estándares de Alta Disponibilidad (Silicon Valley / Tel Aviv).
# Absorbe el 90%+ de los impactos de lectura SQL y gestiona la RAM dinámicamente.
# ==============================================================================
import os

REDIS_URL = os.environ.get('REDIS_URL', None)

if REDIS_URL:
    # 🚀 CLÚSTER DE ALTO RENDIMIENTO (PRODUCCIÓN)
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": 86400,  # Tiempo de vida por defecto (24 horas)
            "KEY_PREFIX": "fenix_matrix",  # Aislamiento de memoria para evitar colisiones
            "VERSION": 1,      # Control de versionado para invalidaciones masivas
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                # Compresión a nivel de bits (Ahorra un 40% de RAM en Redis)
                "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                # Modo "Bulletproof": Si Redis cae, Django ignora el error de caché en lugar de mostrar Pantalla 500
                "IGNORE_EXCEPTIONS": True, 
                # Blindaje de Red (Timeouts y Reconexiones TCP)
                "SOCKET_CONNECT_TIMEOUT": 5,  # Aborta rápido si la conexión física es imposible
                "SOCKET_TIMEOUT": 5,          # Tiempo máximo esperando respuesta
                "CONNECTION_POOL_KWARGS": {
                    "max_connections": 1000,        # Escalabilidad masiva de nodos
                    "retry_on_timeout": True,       # Auto-sanación de red
                    "health_check_interval": 30,    # Ping proactivo para evitar conexiones fantasmas (Zombies)
                }
            }
        }
    }
    
    # 🔥 EL GOLPE MAESTRO: Mover el motor de sesiones a la memoria RAM (Redis)
    # Evita que PostgreSQL reciba lecturas por cada clic del usuario. Latencia: < 1ms.
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"

else:
    # 🛡️ FALLBACK DE EMERGENCIA LOCAL (DESARROLLO / FAILOVER)
    # Motor ultra-optimizado para no causar Memory Leaks (Fugas de memoria)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "stratos-fallback-matrix",
            "TIMEOUT": 3600,       # Rotación de datos más agresiva localmente (1 hora)
            "MAX_ENTRIES": 10000,  # Límite estricto. Protege la memoria RAM del servidor
            "CULL_FREQUENCY": 3,   # Cuando llegue a 10k, elimina instantáneamente 1/3 de los datos más viejos
        }
    }
    
    # Mantenemos las sesiones en base de datos si estamos en entorno local estricto
    SESSION_ENGINE = "django.contrib.sessions.backends.db"

# ==============================================================================
# 🔐 BLINDAJE CRIPTOGRÁFICO DE SESIONES (SEGURIDAD MILITAR)
# ==============================================================================
# Dado que usamos cachés in-memory ultrarrápidos para autorizar usuarios, 
# la cookie en el navegador debe ser impenetrable.

# Expiración estricta de inactividad (Ej: 12 horas de caducidad automática)
SESSION_COOKIE_AGE = 43200 
# Inmunidad absoluta contra lectura por inyección JavaScript (Bloquea XSS)
SESSION_COOKIE_HTTPONLY = True 
# Evita secuestro de sesión permitiendo su envío solo por canales encriptados (HTTPS)
SESSION_COOKIE_SECURE = True 
# Mitigación agresiva contra ataques CSRF (Cross-Site Request Forgery)
SESSION_COOKIE_SAMESITE = 'Lax' 
# Forza el cierre de sesión si el usuario cierra el navegador por completo
SESSION_EXPIRE_AT_BROWSER_CLOSE = True